My_app/urls.py
from django.urls import path, re_path
from . import views

urlspatterns = [
    path("", views.home, name="home")
  
]

my_project/urls.py
from django.contrib import admin
from django.urls import path
from My_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),  
    path('addnew',views.addnew, name='addnew'), 
    path('edit/<int:id>', views.edit, name='edit'),  
    path('update/<int:id>', views.update, name='update'),  
    path('delete/<int:id>', views.destroy, name='destroy'),  
    
]

My_app/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User




#This class is used to create EMPLOYEE Table.
class Employee(models.Model):  
    name = models.CharField(max_length=100)  
    email = models.EmailField()  
    contact = models.CharField(max_length=15) 
   
    class Meta:  
        db_table = "tblemployee"

My_app/forms.py
from django import forms  
from My_app.models import Employee  
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = ['name', 'contact', 'email'] 
        widgets = { 'name': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'email': forms.EmailInput(attrs={ 'class': 'form-control' }),
            'contact': forms.TextInput(attrs={ 'class': 'form-control' }),
      }

My_app/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from My_app.forms import EmployeeForm  
from My_app.models import Employee  
 

#This function is used to ADD a single record  
def addnew(request):  
    if request.method == "POST":  
        form = EmployeeForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/')  
            except:  
                pass
    else:  
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form})  
 
 
#This function is used to LIST all the employees
def index(request):  
    employees = Employee.objects.all()  
    return render(request,"show.html",{'employees':employees})  
 
 
#This function is used to link to edit page
def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'edit.html', {'employee':employee})  
 
 
#This function is used to UPDATE a single record
def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/")  
    return render(request, 'edit.html', {'employee': employee})  
 
#This function is used to DELETE a single record    
def destroy(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/") 

#This function will show the home page
def home(request):
    return render(request, "home.html")

My_app/templates/edit.html
<!-- This template file is used to show a the table of the employees -->
{% extends "base.html" %}
  
{% block title %}Add New Employee Records{% endblock title %}
  
{% block content %}
<div class="col-md-12">
    <form method="POST" class="post-form" action="/update/{{employee.id}}">  
    {% csrf_token %}  
    <div class="container">   
        <div class="col-12">  
            <h3>Update Details</h3>  
        </div> 
        <div class="mb-3"> 
            <label>Employee ID:</label>  
            <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ employee.id }}"/>    
        </div> 
        <div class="mb-3"> 
            <label>Name:</label>  
            <input type="text" class="form-control" name="name" id="id_name" required maxlength="100" value="{{ employee.name }}" />  
        </div> 
        <div class="mb-3"> 
            <label>Email:</label>  
            <input type="email" class="form-control" name="email" id="id_email" required maxlength="254" value="{{ employee.email }}" />  
        </div> 
        <div class="mb-3"> 
            <label>Contact:</label>  
            <input type="text" class="form-control" name="contact" id="id_contact" required maxlength="15" value="{{ employee.contact }}" />  
        </div> 
        <div class="mb-3"> 
            <button type="submit" class="btn btn-success btn-lg">Update</button>  
        </div> 
    </div>  
    </form>  
{% endblock content %}

My_app/templates/index.html
<!-- This template file is used to ADD a record to the table of the employees -->

{% extends "base.html" %}
  
{% block title %}Add New Employee Records{% endblock title %}
  
{% block content %}
<div class="col-md-12">    
    <form method="POST" class="post-form" action="/addnew">  
    {% csrf_token %}  
    <div class="container">  
        <div class="col-12">  
        <h3>Enter Details</h3>  
        </div>    
     
        <div class="mb-3"> 
            <label>Name:</label>  
            {{ form.name }}   
        </div> 
        <div class="mb-3"> 
            <label>Email:</label>  
            {{ form.email }}   
        </div>  
        <div class="mb-3"> 
            <label>Contact:</label>  
            {{ form.contact }}   
        </div>
        <div class="mb-3"> 
            <button type="submit" class="btn btn-primary">Submit</button>    
        </div> 
    </div>  
    </form>  
</div> 
{% endblock content %} 

My_app/templates/show.html
<!-- This template file is used to show the table of the employees -->

{% extends "base.html" %}
  
{% block title %} Demo - EMS{% endblock title %}
  
{% block content %}
 <div class="col-md-12">
        <span ><a href="/addnew" class="btn btn-primary">Add New Record</a></span>  
        <div style="margin: 10px;" class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
        <thead>
            <th><input type="checkbox" id="checkall" /></th>
            <th>ID</th>
            <th>Employee Name</th>
            <th>Employee Email</th>
            <th>Employee Contact</th>
            <th>Edit</th>
            <th>Delete</th>
        </thead>
        <tbody>
        {% for employee in employees %}  
            <tr>  
            <td><input type="checkbox" class="checkthis" /></td>
            <td>{{ employee.id }}</td>  
            <td>{{ employee.name }}</td>  
            <td>{{ employee.email }}</td>  
            <td>{{ employee.contact }}</td>  
            <td><a href="/edit/{{ employee.id }}" class="btn btn-primary">Edit</a></td>
            <td><a href="/delete/{{ employee.id }}" class="btn btn-danger">Delete</a></td>  
            </tr>  
        {% endfor %} 
        </tbody>
        </table>
        </div>
    </div>
{% endblock content %}